baseURL = 'https://k2mts.org/'
languageCode = 'en-us'
title = 'k2mts.org'
theme = "ananke"
publishdir = "../"

[params]
  favicon = ""
  site_logo = ""
  description = "k2mts.org"
  facebook = ""
  twitter = "https://twitter.com/k2mts"
  instagram = ""
  youtube = "https://youtube.com/mstyne"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = "https://vhf-chat.slack.com"
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/k2mts-post-flood-minimalism.jpeg"
  recent_posts_number = 2
